apiVersion: 1

datasources:
  - name: Prometheus
    uid: geocustody-prometheus
    type: prometheus
    access: proxy
    url: http://geocustody-prometheus:9090
    isDefault: true
    editable: true
